name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - dev
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build
      run: |
        npm i -g vuepress
        npm install
        vuepress build docs

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.ACCESS_TOKEN }}
        cname: mirai-py.originpages.com
        publish_dir: ./docs/.vuepress/dist
        commit_message: ${{ github.event.head_commit.message }}